name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    name: Rust format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install nightly --profile minimal -c rustfmt

      - run: cargo +nightly fmt -- --check

  rust:
    name: Rust lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-protoc@v3

      - run: rustup toolchain install stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

      - run: cargo clippy --all-targets -- -D warnings

  windows_test:
    name: Client test (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-protoc@v3

      - run: rustup toolchain install stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test -p sshx

  web:
    name: Web lint, check, and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm ci

      - run: npm run lint

      - run: npm run check

      - run: npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [rustfmt, rust, web]
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
